## Shape Matching

In [3]:
import cv2
import numpy as np

# Load the shape template or reference image
template = cv2.imread('images/4star.jpg',0)
cv2.imshow('Template', template)
cv2.waitKey()

# Load the target image with the shapes we're trying to match
target = cv2.imread('images/shapestomatch.jpg')
target_gray = cv2.cvtColor(target,cv2.COLOR_BGR2GRAY)

# Threshold both images first before using cv2.findContours
ret, thresh1 = cv2.threshold(template, 127, 255, 0)
ret, thresh2 = cv2.threshold(target_gray, 127, 255, 0)

# Find contours in template
image, contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

# We need to sort the contours by area so that we can remove the largest
# contour which is the image outline
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)

# We extract the second largest contour which will be our template contour
template_contour = contours[1]
print(template_contour)
# Extract contours from second target image
image,contours, hierarchy = cv2.findContours(thresh2, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    # Iterate through each contour in the target image and 
    # use cv2.matchShapes to compare contour shapes
    match = cv2.matchShapes(template_contour, c, 3, 0.0)
    print (match)
    # If the match value is less than 0.15 we
    if match < 0.15:
        closest_contour = c
    else:
        closest_contour = [] 
                
cv2.drawContours(target, [closest_contour], -1, (0,255,0), 3)
cv2.imshow('Output', target)
cv2.waitKey()
cv2.destroyAllWindows()

[[[193  96]]

 [[194  95]]

 [[195  95]]

 [[196  96]]

 [[196  97]]

 [[197  98]]

 [[197 100]]

 [[198 101]]

 [[198 102]]

 [[199 103]]

 [[199 104]]

 [[200 105]]

 [[200 107]]

 [[201 108]]

 [[201 109]]

 [[202 110]]

 [[202 111]]

 [[203 112]]

 [[203 114]]

 [[204 115]]

 [[204 116]]

 [[205 117]]

 [[205 118]]

 [[206 119]]

 [[206 121]]

 [[207 122]]

 [[207 123]]

 [[208 124]]

 [[208 125]]

 [[209 126]]

 [[209 128]]

 [[210 129]]

 [[210 130]]

 [[211 131]]

 [[211 132]]

 [[212 133]]

 [[212 135]]

 [[213 136]]

 [[213 137]]

 [[214 138]]

 [[214 139]]

 [[215 140]]

 [[215 142]]

 [[216 143]]

 [[216 144]]

 [[217 145]]

 [[217 146]]

 [[218 147]]

 [[218 149]]

 [[219 150]]

 [[219 151]]

 [[220 152]]

 [[220 153]]

 [[221 154]]

 [[221 156]]

 [[223 158]]

 [[224 158]]

 [[225 159]]

 [[226 159]]

 [[227 160]]

 [[229 160]]

 [[230 161]]

 [[231 161]]

 [[232 162]]

 [[233 162]]

 [[234 163]]

 [[236 163]]

 [[237 164]]

 [[238 164]]

 [[239 165]]

 [[240 165]]

 [[241